### ISSUE TITLE
Tutorial Capstone

### ISSUE THREAD

**Issue by TomasMikula** [TomasMikula/libretto#12]
To cover:

 - [x] Basics
   - [x] Intro to declarative concurrency using graphical notation
   - [x] (the need for) point free style
   - [x] signals
   - [x] ephemeral signals (#51)
   - [x] distributivity
   - [x] duality of `|+|` and `|&|`
   - [x] recursive types
   - [x] recursively defined components
   - [x] racing
   - [x] using Scala values and functions
   - [x] program equality
   - [x] inversions (#62)
   - [x] higher-order functions (#63)
   - [x] lambda syntax (#49)
   - [x] closure syntax (#65)
 - [ ] sequencing (`Signaling`, `Deferrable`/`Junction`) (#50)
 - [ ] sharing resources (`Comonoid`, pooling, reference counting) (#52)
 - [ ] interfacing with components of the host language (#53)
   - [ ] Embedding host language components into Libretto (resource management and I/O)
   - [ ] Embedding Libretto into the host language (depends on #48)
 - [ ] Streams library (#54)
 - [ ] extended examples
   - [ ] request/response service and client
   - [ ] acks/commiting offsets (e.g. Kafka offsets)
 - [ ] supervision and error recovery (depends on #8)
 - [ ] testing
